### ISSUE TITLE
Rolling release support

### ISSUE THREAD

**Issue by dr460nf1r3** [flakestry/flakestry.dev#26]
Hello! Nice to see another attempt for a flake registry :) 

From what I read in on the publish page, flakestry.dev currently only supports flakes working with tags, is that correct? We would like to publish [Nyx](https://github.com/chaotic-cx/nyx) here, but we don't make use of tags and mostly have daily commits.

**Comment by domenkozar** [comment]
There are two ways to support that:

a) `v1.0.<unix epoch>`
b) `v1.0.<commits>`

The easiest to implement is a) and you can do that today yourself something like:

```yaml
- name: Retrieve unix date time
        shell: bash
        run: echo "TIME=$(date '+%s')" >> $GITHUB_ENV
- uses: flakestry/flakestry-publish@main
              with:
                version: "v1.0.${{ env.TIME }}"

**Comment by PedroHLC** [comment]
The `Fetching the repository` phase in `flakestry/flakestry-publish@main`, seems to try to:
`git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/v0.1.1*:refs/remotes/origin/v0.1.1* +refs/tags/v0.1.1*:refs/tags/v0.1.1`

Which won't work if the tag does not exists, right?

**Comment by domenkozar** [comment]
Good point, currently we assume it's a tag.

Not sure yet what to do about it, probably we should allow releases be just a commit.

**Comment by kip93** [comment]
Would also love to publish here too, but have the same problem.

There might be some other random reference or the such, but these 2 seem to be the core of what would need to be touched:
* [the publish backend](https://github.com/flakestry/flakestry.dev/blob/85e67245a506a6bf1e71da8a6a4c166ea00efa0d/backend/flakestry/api/publish.py#L101)
* [the publish docs](https://github.com/flakestry/flakestry.dev/blob/85e67245a506a6bf1e71da8a6a4c166ea00efa0d/frontend/src/Pages/Publish.elm#L1)

I'll play a bit with it this weekend to enable non-tag releases and hopefully create a PR (:

**Comment by domenkozar** [comment]
That would be fantastic!
