### ISSUE TITLE
add support for NOTE, WARNING and IMPORTANT github markdown syntax

### ISSUE THREAD

**Issue by 9glenda** [flakestry/flakestry.dev#28]
# Render Github markdown syntax

```md
> [!IMPORTANT]
> Render it
```

> [!IMPORTANT] 
> Render it
---
```md
> [!NOTE] 
> Render it
```

> [!NOTE] 
> Render it
---
```md
> [!WARNING] 
> Render it
```
> [!WARNING] 
> Render it

## Example
[Example](https://flakestry.dev/flake/github/9glenda/ocaml-flake/0.1.5) of how it is done currently.

**Comment by domenkozar** [comment]
cc @sandydoo maybe we just need to update the github markdown parser?

**Comment by sandydoo** [comment]
There's probably an extension for it. I'll look into it.

**Comment by sandydoo** [comment]
We can use [marked-alert](https://www.npmjs.com/package/marked-alert) for the rendering and update the CSS generator to include the alert styling.

**Comment by sandydoo** [comment]
🎉 Now to figure out how to ship this...
<img width="1108" alt="Screenshot 2023-10-30 at 19 45 37" src="https://github.com/flakestry/flakestry.dev/assets/7572407/55112dc8-e106-4367-8cf4-a8d7c2ee9901">

**Comment by sandydoo** [comment]
Now upstreamed to [github-markdown-css](https://github.com/sindresorhus/github-markdown-css/commit/1363826bdf7720c18d812a5d6c6cceb878293978).
